### PR TITLE
Only install unique peer deps

### PR DESCRIPTION
**Pull request by vtenfys**
Currently, the same peer dependency may be installed multiple times. This PR ensures each unique peer dependency is only installed a single time.

### CODE REVIEW

**Review by andygout — COMMENTED** [review]
Does this only apply to when `peerDependencies` is present in a repo's `package.json`? I have looked at a few repos and cannot see it present in any of them.

Are there some repos that you noticed it in that triggered this change?

**Review by andygout — APPROVED** [review]
I guess there must have been at some point to have justified creating this file in the first place.

Would be useful to know of a few examples of such repos if you encountered any but no sweat if not.

**Comment by davidbailey00** [comment]
This applies when any dependencies of an application have peer dependencies, eg many dependencies in https://github.com/Financial-Times/next-appetite (and by extension the "next-user-facing-app-template" repo) have React as a peer dependency and so React gets installed multiple times.

It's unclear why this helper should be needed by any application - peer dependencies should be explicitly installed in an application when required by other dependencies, so there should be no need for a helper that installs them. In fact I have removed it in a PR for the repo linked above and no problems were caused in CI, as React was already installed explicitly.

**Comment by davidbailey00** [comment]
Example where the same React dependency is re-installed multiple times: https://app.circleci.com/pipelines/github/Financial-Times/next-appetite/121/workflows/2e4fe063-4010-4861-9284-daa5092ace62/jobs/372/parallel-runs/0/steps/0-106

**Comment by davidbailey00** [comment]
I have just realised after sending my last messages, the reason why we are seeing React installed unnecessarily is because `next-appetite` has been upgraded to React 17 (with very few breaking changes from 16) while many of our dependencies include React 16 as a peer dependency, so NPM reports it as 'missing'.

That said, this step is still unnecessary in our case, since React 17 works fine with all the dependencies expecting v16, and in general, an application is expected to include required peer dependencies itself in `package.json` so should not need this helper file.

**Comment by andygout** [comment]
A-ha, thanks for explanation.

A few more questions for my education:
- Presumably unique peer dependencies are those that are the same package and also the same version, i.e. it there was a peer dependency package that appeared twice - one instance using v4 and another using v5 - then in that scenario both instances would be installed?
- Will `package-lock.json` help with this scenario (as we are now introducing that into repos)? (I am thinking out loud with this question and there may be no immediate answer so don't worry if there isn't.)

**Comment by davidbailey00** [comment]
> Presumably unique peer dependencies are those that are the same package and also the same version, i.e. it there was a peer dependency package that appeared twice - one instance using v4 and another using v5 - then in that scenario both instances would be installed?

Correct, although in this case the latter version to be installed would take precedence since NPM doesn't support installing multiple versions of the same dependency in a single application, unless [using an alias](https://stackoverflow.com/a/56134858) which we are not doing. This will function the same before and after this PR.

> Will `package-lock.json` help with this scenario (as we are now introducing that into repos)? (I am thinking out loud with this question and there may be no immediate answer so don't worry if there isn't.)

`package-lock.json` doesn't make too much of a difference here since we already have another helper that runs `npm update`, so all dependencies should be on the latest version matching the `package.json` semver range (eg `^7.0.0` = latest `7.x.x`) regardless of whether a `package-lock.json` is present. (That brings up another question - do we still need the `npm update` helper given we're now starting to use `package-lock.json` to ensure consistency?)

Even if we didn't have the update helper, having `package-lock.json` or not wouldn't really make a difference unless a dependency changes its peer dependencies amidst a minor release (and thus not conform to semver) and since the issue is more about whether correct peer dependencies of an application's dependencies are included in its `package.json`.

**Pull request closed without merging**
